### ISSUE TITLE
8Puzzle not training

### ISSUE THREAD

**Issue by Arifi** [iridia-ulb/AI-book#3]
Bonjour,

Avec l'option `-r` j'arrive a generer des QTables, elles font rien de special, mais quand j'essaye de les entrainer rien ne se passe et l'appli plante.

Après debugage, je me suis rendu compte que le code ne sors pas de la boucle `while not solvableGame:` dans le fichier `EightPuzzle_RL.py` a la ligne [426](https://github.com/iridia-ulb/AI-book/blob/c5518465d6335370aa2db2eb05cf44f841042369/8Puzzle/EightPuzzle_RL.py#L426)

Je suis pas sur de ce que j'avance, je suis débutant et perdus, merci d'avance pour tout aide

**Comment by Arifi** [comment]
Ci-joint mes QTables

[QTable.zip](https://github.com/iridia-ulb/AI-book/files/12448094/QTable.zip)

**Comment by KenN7** [comment]
Bonjour,
Merci de votre retour, il y avait effectivement un bug dans l'entrainement du 8Puzzle
Je viens de mettre à jour la version en ligne, vous pouvez télécharger la nouvelle version qui corrige le problème :)

**Comment by Arifi** [comment]
Bonjour @KenN7 ,
Oui ça marche mnt :)

**Comment by Arifi** [comment]
Salut @KenN7 , je voudrais savoir si cette AI (8Puzzle) utilise le CPU ou le GPU ? merci d'avance

**Comment by Arifi** [comment]
Merci @KenN7 pour ces précisions !
